#!/usr/bin/env python3
"""Quality gate: commit subjects follow the project's conventional-commit style.

    tipo(escopo opcional): descrição

Allowed types: feat, fix, docs, test, ci, build, chore, style, refactor, perf. The
scope is lowercase (letters, digits, `-`, `_`, `.`, `/`); `!` after the type/scope marks
a breaking change. Merge and revert commits generated by git are accepted as they are.

Usage:
    scripts/check-commits.py                 # commits in origin/main..HEAD
    scripts/check-commits.py BASE..HEAD      # an explicit range (what CI passes)
    scripts/check-commits.py --all           # the whole history
    scripts/check-commits.py --message-file .git/COMMIT_EDITMSG   # commit-msg hook
"""

import re
import subprocess
import sys

TYPES = ("feat", "fix", "docs", "test", "ci", "build", "chore", "style", "refactor", "perf")
SUBJECT = re.compile(
    r"^(?:" + "|".join(TYPES) + r")"  # type
    r"(?:\([a-z0-9][a-z0-9._/-]*\))?"  # optional scope
    r"!?: "  # optional breaking-change marker, then ": "
    r"\S.*$"  # a description that does not start with a space
)
# Subjects git writes itself; they carry no type and that is fine.
GENERATED = re.compile(r'^(Merge (branch|pull request|remote-tracking branch) |Revert ")')
MAX_SUBJECT = 100


def problems(subject: str) -> list[str]:
    if GENERATED.match(subject):
        return []
    found = []
    if not SUBJECT.match(subject):
        found.append(
            "assunto fora do padrão 'tipo(escopo): descrição' "
            f"(tipos: {', '.join(TYPES)})"
        )
    if len(subject) > MAX_SUBJECT:
        found.append(f"assunto com {len(subject)} caracteres (máximo {MAX_SUBJECT})")
    if subject.rstrip() != subject:
        found.append("espaço no fim do assunto")
    return found


def commits(rev_range: str | None) -> list[tuple[str, str]]:
    args = ["git", "log", "--format=%H%x09%s", "--no-merges"]
    args += [rev_range] if rev_range else []
    out = subprocess.run(args, check=True, capture_output=True, text=True).stdout
    return [tuple(line.split("\t", 1)) for line in out.splitlines() if line]


def main(argv: list[str]) -> int:
    if len(argv) >= 2 and argv[0] == "--message-file":
        with open(argv[1], encoding="utf-8") as fh:
            # The subject is the first line that is not a git comment.
            lines = [l for l in fh.read().splitlines() if not l.startswith("#")]
        subject = next((l for l in lines if l.strip()), "")
        issues = problems(subject)
        for issue in issues:
            print(f"commit-msg: {issue}\n  -> {subject}", file=sys.stderr)
        return 1 if issues else 0

    if argv and argv[0] == "--all":
        rev_range = None
    elif argv:
        rev_range = argv[0]
    else:
        rev_range = "origin/main..HEAD"

    checked, bad = 0, 0
    for sha, subject in commits(rev_range):
        checked += 1
        for issue in problems(subject):
            bad += 1
            print(f"{sha[:7]} {issue}\n        {subject}")
    print(f"commits: {checked} verificados, {bad} problema(s)")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
